'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Case.AppsRibbon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAACDdcelsQw11iX67kXJpLrCoFRLuE9IRx9L5Wr6PzSOeAAAAAAOgAAAAAIAACAAAACCuSaEtrlKNOqpTuVt8Sn+oshfOHCzdR7P3Wnlq3a9zBAAAAD7+FRSmfc62ZYfJxR6lcQyQAAAAG1cDpyxrpVfEs9L9JefZ7Ix9Ikt5eFMKDZJWNQlvc8ul1pSFgLkKFZ2xbzqE8+BCx+SnGDA2Z3MFDcCPX85Ao4=.
        '''</summary>
        Friend ReadOnly Property br1() As String
            Get
                Return ResourceManager.GetString("br1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAACM+MwnzH1mCFtwWUUQ3KeInaf0oL5ld0IzUkVY2CLebwAAAAAOgAAAAAIAACAAAADbjFm5UG03phY7ZDKQChqt6eFXvK+wqKk1o3ct1In9tiAAAACLTwE10lPZSAMzolcwO6KiLdv+c76s7lwD37LW6KYUb0AAAAD8sNDd7cfr6JntGnYTxqTi6W1vkPFupI7rgRbCbXaRpV+3Dn/sbulEUv0WLClYfUl7h4sbvtRk7nkSyHzg5N4u.
        '''</summary>
        Friend ReadOnly Property br2() As String
            Get
                Return ResourceManager.GetString("br2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAADqv8SZ7/ZSiIMjQeqoAvmWypSrJGGzgrixH469JtZM6wAAAAAOgAAAAAIAACAAAABUgpEEA1+XmYvcev/S2ITA5l4FAfiyqUSAveWlcs624mAAAAAUk0r5tc2/08ND5If1TuNjSb5xKt1GaLJIQ6YMItC5shAFKIoEM9hZholLrLurW3GiYXcEf/qlZBDH0GhIOw/wiydn1SBpgMqZjR8jIxcApV6OvOb9FJbB5ZeXfcCA6/VAAAAALKNuYHp6su8HXMaReM5VbIzTRzN2hHVvf271LKfjbi8V2t6M5W3BQtrALlKfRXnHYEpJ8aGeNk+10OVe2d1DlA==.
        '''</summary>
        Friend ReadOnly Property br3() As String
            Get
                Return ResourceManager.GetString("br3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAACYOnD1g9PabinxgfdV5UdYdoDOe3XmfHnCu+iwOftcIgAAAAAOgAAAAAIAACAAAABX/bYncjWwuMiO/KgWPx6FqCPEDTofw0aJLHqEhdF3URAAAADCYW43GkG6cTUaOqSCVEzlQAAAANHqlIogqHqOV9jtyT6bfau9O7Nvn/F4UOA1R9J/qAJ1+OxwnBSLmHiw28JqrKkrdX586T2OlaeDR9BlsuqhCtE=.
        '''</summary>
        Friend ReadOnly Property st1() As String
            Get
                Return ResourceManager.GetString("st1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAAAxGetfch2CYCORi96+9dWO4XZxynXlqabkeFoFgJtUAAAAAAAOgAAAAAIAACAAAAAeFfUTlWMq4AFGemHCNRyBheYFxcIIFeJpGxIubgq+ICAAAACpEY9JUp0sZbf5J7L5goHPCazjHlFV8mm70HxzLCf5fkAAAACssqSv5Uik15mDSEr1qNfMF1oH/IpV6HqOuU1VgM3fv0wtbMXHXH0Lf3p7c4H6NQ0paDM4ipyGNNj+h3vIVy3X.
        '''</summary>
        Friend ReadOnly Property st2() As String
            Get
                Return ResourceManager.GetString("st2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA6AdYamLG6U+ieBjJPb5tOAAAAAACAAAAAAAQZgAAAAEAACAAAABLIZRSQTy0QU6qeF+E4hHLvRUmhU5tGQl0j+W5reLrjwAAAAAOgAAAAAIAACAAAAAbGyOVX+nf+H0LlsyQqPpiqL0c2PwlETwFySR12m8O92AAAAD+682ZK6VKtx1Y8GV5z6WHkCzTLg5HsX4KDwMFxSKR5T+YfXi6NVAV2PHyssy/5aqH+miGBeVqXtqovWNNurxG1viEkWE62k6opvmtAos08gUP7JcNFFiYXZIBYxTAzZ9AAAAA6ztl5GVIwf1w72Yo5Otbuj38ugfSFm0JYP9Exd5PRlwMvhoLpkPVCDFs/TBh3snG4dJHA5mEIVhcXecCqDDwfw==.
        '''</summary>
        Friend ReadOnly Property st3() As String
            Get
                Return ResourceManager.GetString("st3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
